### ISSUE TITLE
Implement Row widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#1]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by KarthikS373** [comment]
Sir please assign me this

**Comment by rktejesh** [comment]
ATB👍

**Comment by KarthikS373** [comment]
Have send a PR for the same
