### ISSUE TITLE
Implement FloatingActionButton Widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#12]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by KarthikS373** [comment]
Sir I would like to take this up please assign me

**Comment by rktejesh** [comment]
LGTM👍

**Comment by TsarPrince** [comment]
floatingActionButton.dart is giving some error in mine, did I missed something?
@rktejesh @KarthikS373 
![image](https://user-images.githubusercontent.com/31801256/158010042-90b47fc1-50d2-42b2-ac6c-ceee296e7bf3.png)

**Comment by KarthikS373** [comment]
@TsarPrince U need to install a 3rd party dependency to use fab_circular_menu

`flutter pub add fab_circular_menu`
Run this on terminal

**Comment by TsarPrince** [comment]
Okay so `fab_circular_menu` was already installed in dependencies. Running `flutter pub upgrade fab_circular_menu` fixed the issue. Thanks @KarthikS373 !

**Comment by rktejesh** [comment]
Check if the library is mentioned in pubspec.yaml. Then all you need to do is flutter pub get. Pubspec is the package manger similiar to package.json in node. Btw try not to use 3rd party libraries since this project prioritises on flutter's core features.
