### ISSUE TITLE
Implement Icon Widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#13]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by TsarPrince** [comment]
@rktejesh  sir I would like to work on this, please assign it.

**Comment by rktejesh** [comment]
Sure 👍
