### ISSUE TITLE
Implement a splash screen

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#18]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Build a splash screen with either a design logo of your choice or just the text - "FluttaDex". Points will also be awarded on the design of logo and screen. Creativity in the implementation will fetch you more points ;)

**Comment by KarthikS373** [comment]
Sir I would like to take this up but can you please specify where to build this - as a SplashScreenImplementation() or as the one launches with the app and then route to widget list?

**Comment by rktejesh** [comment]
Sure. Implement a splashscreen when the app launches with a 2-3s time delay and redirect it to the widget listview.
