### ISSUE TITLE
Implement Column Widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#2]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by KarthikS373** [comment]
Sir can I get this assigned

**Comment by rktejesh** [comment]
Sure👍
