### ISSUE TITLE
Create a form using Form Widget with parameters of profile details of a college student

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#36]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by TsarPrince** [comment]
Sir can you please assign this to me.

**Comment by rktejesh** [comment]
Sure go ahead 👍
