### ISSUE TITLE
Implement BottomNavigationBar Widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#4]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by Saavrm26** [comment]
may i be assigned to this issue

**Comment by rktejesh** [comment]
Sure👍

**Comment by rktejesh** [comment]
@Saavrm26 Are you facing any issue?

**Comment by Saavrm26** [comment]
No sir i've rectified the issue

**Comment by Saavrm26** [comment]
@rktejesh should i add more features in the bottom navigationbar or should I move to another issue?

**Comment by rktejesh** [comment]
My bad. Reference the issue from next PR. Helps keep track of the solved issues.

**Comment by rktejesh** [comment]
> @rktejesh should i add more features in the bottom navigationbar or should I move to another issue?
> 

Take up another issue👍
