### ISSUE TITLE
Implement Drawer Widget

### ISSUE THREAD

**Issue by rktejesh** [rktejesh/Fluttadex#8]
Read the [contribution guidelines](https://github.com/rktejesh/Fluttadex/blob/master/CONTRIBUTING.md) and [readme](https://github.com/rktejesh/Fluttadex#readme)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/rktejesh)[](https://github.com/). Ask to get assigned this issue. Add the implementation and description. Creativity in the implementation will fetch you more points ;)

**Comment by KarthikS373** [comment]
Sir can I have this

**Comment by rktejesh** [comment]
Sure👍
